<script lang="ts">
  import { onMount, beforeUpdate, afterUpdate } from "svelte";
  import { fly } from "svelte/transition";
  import { backInOut } from "svelte/easing";
  import pillStore, {
    PillTextType,
    PillBehavior,
    PillShape
  } from "./pillStore";
  import store from "../../store";
  import { formatTokenAmount } from "../../utils";

  let currentText = "";
  let currentTextType = undefined;
  let currentShape: PillShape = undefined;
  let xtzPriceTrend: "up" | "down" | "same" | "none" = "none";
  let isAnimated = false;
  let isShaking = false;

  const shapeToClass = (p: PillShape): string => {
    switch (p) {
      case PillShape.NORMAL:
        return "normal";
      case PillShape.LARGE:
        return "large";
    }
  };

  const anim = () => {
    isAnimated = true;
    setTimeout(() => {
      isAnimated = false;
    }, 400);
  };

  const animToLargeThenToNormal = () => {
    isAnimated = true;
    pillStore.switchShape(PillShape.LARGE);
    setTimeout(() => {
      isAnimated = false;
    }, 400);

    setTimeout(() => {
      isAnimated = true;
      pillStore.update({
        text: `1 XTZ = ${formatTokenAmount($store.xtzExchangeRate, 2)} ${
          $store.localStorage.getFavoriteFiat().code
        }`,
        type: PillTextType.XTZ_PRICE
      });
      pillStore.switchShape(PillShape.NORMAL);
      setTimeout(() => {
        isAnimated = false;
      }, 400);
    }, 3000);
  };

  onMount(() => {
    currentShape = $pillStore.shape;
  });

  beforeUpdate(() => {
    if (
      $pillStore.textType === PillTextType.TOKEN_PRICE &&
      (currentText !== $pillStore.text ||
        currentTextType !== $pillStore.textType)
    ) {
      // new token price info in pill
      animToLargeThenToNormal();
    } else if (
      currentShape == PillShape.NORMAL &&
      $pillStore.shape === PillShape.LARGE
    ) {
      anim();
    } else if (
      currentShape == PillShape.LARGE &&
      $pillStore.shape === PillShape.NORMAL
    ) {
      anim();
    } else if ($pillStore.behavior === PillBehavior.SHAKING_TOP) {
      isShaking = true;
    } else {
      isShaking = false;
    }
  });

  afterUpdate(() => {
    if ($pillStore.textType === PillTextType.XTZ_PRICE) {
      const start = $store.xtzPriceHistoric[0].price;
      const end =
        $store.xtzPriceHistoric[$store.xtzPriceHistoric.length - 1].price;
      if (start > end) {
        xtzPriceTrend = "down";
      } else if (start < end) {
        xtzPriceTrend = "up";
      } else if (start === end) {
        xtzPriceTrend = "same";
      } else {
        xtzPriceTrend = "none";
      }
    }

    setTimeout(() => {
      currentText = $pillStore.text;
      currentTextType = $pillStore.textType;
      currentShape = $pillStore.shape;
    }, 100);
  });
</script>

<style lang="scss">
  @import "../../styles/settings.scss";

  .pill {
    position: absolute;
    bottom: 30px;
    left: 0;
    right: 0;
    margin: 0 auto;
    display: grid;
    align-items: center;
    background-color: $dark-cornflower-blue;
    color: white;
    font-size: 0.8rem;
    padding: 10px 30px;
    border-radius: 60px;
    text-align: center;
    box-shadow: rgba(50, 50, 93, 0.25) 0px 13px 27px -5px,
      rgba(0, 0, 0, 0.3) 0px 8px 16px -8px;
    z-index: 999;

    &.normal {
      width: 150px;
      height: 25px;
      grid-template-columns: 5% 90% 5%;

      &.animated {
        -webkit-animation: retract 0.2s linear backwards;
        animation: retract 0.2s linear backwards;
      }
    }

    &.large {
      width: 300px;
      height: 30px;
      grid-template-columns: 10% 80% 10%;

      &.animated {
        -webkit-animation: extend 0.2s linear backwards;
        animation: extend 0.2s linear backwards;
      }
    }

    &.shake-top {
      -webkit-animation: shake-top 0.8s cubic-bezier(0.455, 0.03, 0.515, 0.955)
        both;
      animation: shake-top 0.8s cubic-bezier(0.455, 0.03, 0.515, 0.955) both;
    }

    &.minimized {
      height: 25px;
      width: 25px;
      border-radius: 50%;
      padding: 10px;
      cursor: pointer;
      margin: 0;
      left: 95%;
    }

    .pill__middle {
      display: flex;
      justify-content: center;
      align-items: center;
    }
  }

  @keyframes extend {
    0% {
      width: 150px;
      height: 25px;
      opacity: 0;
    }
    100% {
      width: 300px;
      height: 30px;
      opacity: 1;
    }
  }

  @keyframes retract {
    0% {
      width: 300px;
      height: 30px;
    }
    100% {
      width: 150px;
      height: 25px;
    }
  }

  /* ----------------------------------------------
 * Generated by Animista on 2022-10-11 19:34:48
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

  /**
 * ----------------------------------------
 * animation shake-top
 * ----------------------------------------
 */
  @-webkit-keyframes shake-top {
    0%,
    100% {
      -webkit-transform: rotate(0deg);
      transform: rotate(0deg);
      -webkit-transform-origin: 50% 0;
      transform-origin: 50% 0;
    }
    10% {
      -webkit-transform: rotate(2deg);
      transform: rotate(2deg);
    }
    20%,
    40%,
    60% {
      -webkit-transform: rotate(-4deg);
      transform: rotate(-4deg);
    }
    30%,
    50%,
    70% {
      -webkit-transform: rotate(4deg);
      transform: rotate(4deg);
    }
    80% {
      -webkit-transform: rotate(-2deg);
      transform: rotate(-2deg);
    }
    90% {
      -webkit-transform: rotate(2deg);
      transform: rotate(2deg);
    }
  }
  @keyframes shake-top {
    0%,
    100% {
      -webkit-transform: rotate(0deg);
      transform: rotate(0deg);
      -webkit-transform-origin: 50% 0;
      transform-origin: 50% 0;
    }
    10% {
      -webkit-transform: rotate(2deg);
      transform: rotate(2deg);
    }
    20%,
    40%,
    60% {
      -webkit-transform: rotate(-4deg);
      transform: rotate(-4deg);
    }
    30%,
    50%,
    70% {
      -webkit-transform: rotate(4deg);
      transform: rotate(4deg);
    }
    80% {
      -webkit-transform: rotate(-2deg);
      transform: rotate(-2deg);
    }
    90% {
      -webkit-transform: rotate(2deg);
      transform: rotate(2deg);
    }
  }
</style>

{#if $pillStore.show && $store.isAppReady && !$pillStore.minimized}
  <div
    class={`pill ${shapeToClass($pillStore.shape)} ${
      isAnimated ? "animated" : ""
    } ${isShaking ? "shake-top" : ""}`}
    transition:fly={{ duration: 400, y: 100, easing: backInOut }}
    on:click={() => pillStore.minimize()}
  >
    <div class="pill__left">
      {#if $pillStore.textType === PillTextType.HARVEST_REWARDS}
        <span class="material-icons-outlined"> agriculture </span>
      {:else if $pillStore.textType === PillTextType.SUCCESS}
        <span class="material-icons-outlined" style="color:green">
          thumb_up
        </span>
      {:else if $pillStore.textType === PillTextType.TRANSFER_OP}
        <span class="material-icons-outlined"> send </span>
      {:else}
        <span> &nbsp; </span>
      {/if}
    </div>
    <div class="pill__middle">{currentText}</div>
    <div class="pill__right">
      {#if $pillStore.textType === PillTextType.XTZ_PRICE && xtzPriceTrend === "up"}
        <span class="material-icons-outlined" style="color:green">
          trending_up
        </span>
      {:else if $pillStore.textType === PillTextType.XTZ_PRICE && xtzPriceTrend === "down"}
        <span class="material-icons-outlined" style="color:red">
          trending_down
        </span>
      {:else if $pillStore.textType === PillTextType.XTZ_PRICE && xtzPriceTrend === "same"}
        <span class="material-icons-outlined"> trending_flat </span>
      {:else if $pillStore.textType === PillTextType.ERROR}
        <span class="material-icons-outlined" style="color:red">
          thumb_down
        </span>
      {:else}
        &nbsp;
      {/if}
    </div>
  </div>
{:else if $store.isAppReady && $pillStore.minimized}
  <div
    class="pill minimized"
    on:click={() => pillStore.maximize()}
    transition:fly={{ duration: 400, y: 100, easing: backInOut }}
  >
    <span class="material-icons-outlined"> notifications_paused </span>
  </div>
{/if}
