<script lang="ts">
  import { onMount, afterUpdate, createEventDispatcher } from "svelte";
  import { slide } from "svelte/transition";
  import type { IconValue } from "../../types";

  export let options: { icons: IconValue[]; name: string }[],
    selected: string,
    displaySelection: boolean;

  let openOptions = false;
  let hoveredOption = 0;
  let mouseDirection: "up" | "down" | null = null;
  let selection = "";
  let sortByChars = "";
  const dispatch = createEventDispatcher();

  const sortOptions = (event: EventTarget) => {
    const val = event.target.value;
    if (!val) {
      selection = "";
      sortByChars = "";
      dispatch("new-selection", null);
    } else {
      openOptions = true;
      sortByChars = val;
    }
  };

  onMount(() => {
    if (selected) {
      selection = selected;
    }
  });

  afterUpdate(() => {
    if (selected && selected !== selection) {
      selection = selected;
    }
  });
</script>

<style lang="scss">
  @import "../../styles/settings.scss";

  $input-width: 130px;
  $button-width: 50px;
  $height: 1.5rem + 0.5rem;

  .select-box {
    width: 100%;
    display: flex;
    justify-content: center;
    position: relative;
    width: $button-width + $input-width + $button-width;
    height: $height;

    input[type="text"] {
      margin: 0px;
      padding: 5px;
      border-top-left-radius: 0px;
      border-bottom-left-radius: 0px;
      border-top-right-radius: 0px;
      border-bottom-right-radius: 0px;
      background-color: white;
      width: $input-width;
    }

    button {
      margin: 0px;
      padding: 5px;
      border-top-left-radius: 0px;
      border-bottom-left-radius: 0px;
      border-top-right-radius: 5px;
      border-bottom-right-radius: 5px;
      border: none;
      background-color: white;
      cursor: pointer;
      width: $button-width;
    }

    .token-icon {
      width: $button-width;
      background-color: white;
      border-top-left-radius: 5px;
      border-bottom-left-radius: 5px;
      border-top-right-radius: 0px;
      border-bottom-right-radius: 0px;
      display: flex;
      align-items: center;
      padding: 5px;

      img {
        width: 25px;
        height: 25px;
      }
    }
  }

  .select-box-options {
    position: absolute;
    top: $height + 0.1rem;
    left: 0px;
    background-color: white;
    max-height: 200px;
    overflow: auto;
    color: $container-bg-color;
    width: $button-width + $input-width + $button-width;
    z-index: 10;

    div {
      text-align: left;
      padding: 10px;
      cursor: pointer;
      display: flex;
      align-items: center;
      transition: 0.3s;

      &:hover {
        background-color: lighten($bg-color, 50);
      }

      &:hover img.slide-in-top {
        -webkit-animation: slide-in-top 0.3s
          cubic-bezier(0.25, 0.46, 0.45, 0.94) both;
        animation: slide-in-top 0.3s cubic-bezier(0.25, 0.46, 0.45, 0.94) both;
      }
      &:hover img.slide-in-bottom {
        -webkit-animation: slide-in-bottom 0.3s
          cubic-bezier(0.25, 0.46, 0.45, 0.94) both;
        animation: slide-in-bottom 0.3s cubic-bezier(0.25, 0.46, 0.45, 0.94)
          both;
      }

      img {
        width: 25px;
        height: 25px;
      }
    }
  }

  /* ----------------------------------------------
 * Generated by Animista on 2021-8-5 9:20:34
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

  /**
 * ----------------------------------------
 * animation slide-in-top
 * ----------------------------------------
 */
  @-webkit-keyframes slide-in-top {
    0% {
      -webkit-transform: translateY(-50px);
      transform: translateY(-50px);
      opacity: 0;
    }
    100% {
      -webkit-transform: translateY(0);
      transform: translateY(0);
      opacity: 1;
    }
  }
  @keyframes slide-in-top {
    0% {
      -webkit-transform: translateY(-50px);
      transform: translateY(-50px);
      opacity: 0;
    }
    100% {
      -webkit-transform: translateY(0);
      transform: translateY(0);
      opacity: 1;
    }
  }

  /**
 * ----------------------------------------
 * animation slide-in-bottom
 * ----------------------------------------
 */
  @-webkit-keyframes slide-in-bottom {
    0% {
      -webkit-transform: translateY(50px);
      transform: translateY(50px);
      opacity: 0;
    }
    100% {
      -webkit-transform: translateY(0);
      transform: translateY(0);
      opacity: 1;
    }
  }
  @keyframes slide-in-bottom {
    0% {
      -webkit-transform: translateY(50px);
      transform: translateY(50px);
      opacity: 0;
    }
    100% {
      -webkit-transform: translateY(0);
      transform: translateY(0);
      opacity: 1;
    }
  }
</style>

<div class="select-box">
  <div class="token-icon">
    {#if selection}
      {#each options.find(opt => opt.name === selection).icons as icon}
        <img src={`images/${icon}.png`} alt={icon + "-token"} />
      {/each}
    {/if}
  </div>
  <input
    type="text"
    placeholder="Select a token"
    value={selection}
    on:input={sortOptions}
  />
  <button on:click={() => (openOptions = !openOptions)}>
    <span class="material-icons"> unfold_more </span>
  </button>
  {#if openOptions}
    <div class="select-box-options" transition:slide={{ duration: 300 }}>
      {#each options.sort((a, b) => a.name
          .toLowerCase()
          .localeCompare(b.name.toLowerCase())) as option, index}
        {#if !sortByChars || (sortByChars && option.name
              .toLowerCase()
              .includes(sortByChars.toLowerCase()))}
          <div
            on:mouseenter={() => {
              const newHoveredOption = index + 1;
              if (newHoveredOption > hoveredOption) {
                mouseDirection = "down";
              } else if (newHoveredOption < hoveredOption) {
                mouseDirection = "up";
              } else {
                mouseDirection = null;
              }
              hoveredOption = newHoveredOption;
            }}
            on:click={() => {
              openOptions = false;
              dispatch("new-selection", option.name);
              if (displaySelection) {
                selection = option.name;
              }
            }}
          >
            {#each option.icons as icon}
              <img
                class:slide-in-top={mouseDirection === "down" &&
                  hoveredOption === index + 1}
                class:slide-in-bottom={mouseDirection === "up" &&
                  hoveredOption === index + 1}
                src={`images/${icon}.png`}
                alt={icon + "-token"}
              />
            {/each}
            &nbsp;
            {option.name}
          </div>
        {/if}
      {/each}
    </div>
  {/if}
</div>
